apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saas-api.fullname" . }}
  labels:
    {{- include "saas-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.JWT_REFRESH_SECRET | quote }}
  