replicaCount: 2

image:
  repository: ghcr.io/jgm1997/mutlitenant-saas-api
  pullPolicy: IfNotPresent
  tag: 'latest'

imagePullSecrets: []

serviceAccount:
  create: true
  name: ''

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: saas-api.local
  tls: false

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

probes:
  liveness:
    path: /health/live
    initialDelaySeconds: 15
    periodSeconds: 20
    failureThreshold: 3
  readiness:
    path: /health/ready
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1

config:
  NODE_ENV: production
  PORT: '3000'
  JWT_EXPIRES_IN: 15m
  JWT_REFRESH_EXPIRES_IN: 7d

secrets:
  DATABASE_URL: ''
  JWT_SECRET: ''
  JWT_REFRESH_SECRET: ''
